### ISSUE TITLE
Missing Initialisers when iterating.

### ISSUE THREAD

**Issue by GarethShapiro** [sketchytech/Iolcos#1]
Interrogating JSONDictionary with a for .. in loop generates missing initialiser messages.

Let me know if the screenshot is not enough.

![screen shot 2015-04-21 at 15 02 39](https://cloud.githubusercontent.com/assets/342749/7253882/8478b588-e837-11e4-8540-3354abbf6676.png)

I've updated with a better screenshot.  The first one was rubbish!

**Comment by sketchytech** [comment]
Please download the latest [ValueEnum.swift](https://github.com/sketchytech/Aldwych_JSON_Swift/blob/master/Sources/ValueEnum.swift) file and let me know if it fixes the problem

**Comment by GarethShapiro** [comment]
Certainly does.  Thanks for your very quick response.
